### ISSUE TITLE
switch to cargo-i18n (using fluent)

### ISSUE THREAD

**Issue by GlenDC** [plabayo/news#37]
<https://github.com/kellpossible/cargo-i18n>

Instead of the now used <https://crates.io/crates/rust-i18n>.

We would use Fluent, I have good experience with it.

Document as well for translators. Will need to be in text for now as I am not aware of any editors to help us.

**Comment by GlenDC** [comment]
Not going to go for it. doesn't seem to be actively maintained with important issues such as Fluent validation (https://github.com/kellpossible/cargo-i18n/issues/31) not being actively in there. On top of that there is no interaction expected, so no need for any variables even. Going to keep it simple key-string for now, we can always migrate to something more advanced if needed.

**Comment by kellpossible** [comment]
@GlenDC thanks for feedback, definitely open to contributions for https://github.com/kellpossible/cargo-i18n/issues/31 if you have time, I'm happy to review.
